- README.md
- example/main.go
- go.mod
- tests/integration/clerk_test.go
- tests/integration/emails_test.go
- tests/integration/sms_test.go
- tests/integration/users_test.go
Because we're still in version 1, we need to get rid of the version in the module path according to this: https://golang.org/ref/mod#major-version-suffixes
That was the reason I couldn't add the SDK as a dependency in the `clerk_go` project.
> Got rid of v1 in module path to make it go-gettable

- clerk/clerk.go
- clerk/clerk_test.go
With the previous implementation, if the given URL was not ending with `/`, then the SDK would remove the final path. This is now fixed, when creating the client, we check if the given URL has a trailing `/` and if not, we add one.
There is also an additional function to create the `clerk.Client` which allows you to specify the HTTP Client you want it to use. For example, a user might want to use a client which offers some caching.
> Made URL resolution more robust

- .github/pull_request_template.md
- .github/workflows/tests.yml
- clerk/verification.go
- clerk/verification_test.go
- tests/integration/clerk_test.go
- tests/integration/verification_test.go
Modified verification algorithm to rely solely on the existence of `_clerk_session_id` query parameter.
In particular:
* If `_clerk_session_id` is missing, use last active session
* If `_clerk_session_id` is present use the given session
https://www.notion.so/clerkdev/Align-Go-SDK-middleware-with-Node-SDK-middleware-5b12e9e63627486d8678df5d1df129e6
> Verification relies solely on existence of _clerk_session_id

- .github/workflows/tests.yml
- clerk/users.go
- clerk/users_test.go
- tests/integration/clerk_test.go
- tests/integration/users_test.go
- tests/integration/verification_test.go
When updating a user, you can optionally define public and private metadata.
This metadata are JSON objects of any form and will be stored and returned along with the user itself.
https://www.notion.so/clerkdev/User-custom-attributes-29dc3bba4d9442849c9831a09089042c
> Users can have custom public and private metadata

- clerk/clients.go
- clerk/clients_test.go
- clerk/verification.go
- clerk/verification_test.go
Given that most applications will be single-session, we had to simplify the verification process for cases where we were not given a session id.
We modified the response of `/clients/verify` endpoint to return the list of sessions along with the client.
So, we don't need to have an additional call to the backend API anymore to get active session for the client, we can just get it from the returned sessions.
https://www.notion.so/clerkdev/In-single-session-mode-without-_clerk_session_id-come-up-with-strategy-to-use-1-api-request-or-0--ab0fac16668c4dd487f668bd30077e4d
> If no session id is given, get the latest active from client's sessions

- clerk/clerk.go
- clerk/webhooks.go
- clerk/webhooks_test.go
- tests/integration/webhooks_test.go
This PR adds the webhook operations in the Go SDK.
In particular, it adds the following:
* CreateDiahook: Used to create a new Diahook app for the given instance
* RefreshDiahookURL: Returns a new url that can be used to access the Diahook management UI for the given app
* DeleteDiahook: Deletes the Diahook app associated with the given instance
https://www.notion.so/clerkdev/Manage-webhooks-through-the-Dashboard-f744586818814b45828d09f8b6d09701
> Added Webhook operations in SDK

- clerk/webhooks.go
- clerk/webhooks_test.go
Diahook rebranded to Svix.
This PR contains all the necessary changes to keep our codebase up to date.
https://github.com/clerkinc/clerk_go/pull/565
> chore: Rename Diahook to Svix

- .github/workflows/tests.yml
- clerk/clerk.go
- clerk/jwks_cache.go
- clerk/tokens.go
- clerk/tokens_test.go
This PR adds two function utilities in the Go SDK to be used with the upcoming networkless authentication. 
In particular, it adds the following:
- DecodeToken: Return the token claims included in the JWT token **without** verifying it
- VerifyToken: Verify the JWT token and return the token claims
Must be merged after #19
> feat: Introduce DecodeToken and VerifyToken utilities

- clerk/clerk.go
- clerk/middleware.go
- clerk/middleware_test.go
- clerk/tokens.go
- clerk/tokens_test.go
This PR changes the current middleware `WithSession` to also handle session tokens that will be used in the upcoming networkless authentication. If successful adds the JWT claims in the request context so you can easily access them inside a handler. This change should not affect or change the middleware behavior for the current use cases
> feat: Change middleware to also handle AuthV2

- clerk/clerk.go
- clerk/clerk_test.go
- clerk/delete_response.go
- clerk/templates.go
- clerk/templates_test.go
- clerk/users.go
- tests/integration/templates_test.go
Adds support for the following (email & SMS) template CRUD operations:
> feat: Add support for template CRUD operations

- clerk/templates.go
- clerk/templates_test.go
- tests/integration/templates_test.go
Had omitted the `subject` field in my last commit.
> fix: Add subject for email templates

- clerk/templates.go
- clerk/templates_test.go
- tests/integration/templates_test.go
Added support for the `POST /v1/templates/{template_type}/{slug}/preview` backend API endpoint.
> feat: Add support for template previews

- tests/integration/templates_test.go
After the recent changes in the templates endpoint, we need to include the required variables for each template slug, otherwise the integration tests will fail, blocking any new PR
> fix: Templates integration tests to include the required variables per slug

- clerk/clerk.go
- clerk/clerk_options.go
- clerk/clerk_options_test.go
- clerk/clerk_test.go
- clerk/http_utils_test.go
- tests/integration/clerk_test.go
This PR introduces functional options for our client constructor, that allow to override some of the default settings. 
After this change we won't need to export multiple constructor functions (e.g. `clerk.NewClientWithBaseUrl()`), but a single one `clerk.NewClient()` which will accept some optional parameters.
For example if someone wants to provide their own http client
**Before:**
```golang
customHTTPClient := &http.Client{Timeout: time.Second * 30}
c, err := clerk.NewClientWithCustomHTTP("apiKey", clerk.ProdUrl, customHTTPClient)
```
**After:**
```golang
customHTTPClient := &http.Client{Timeout: time.Second * 30}
c, err := clerk.NewClient("apiKey", clerk.WithHTTPClient(customHTTPClient))
```
The old constructor functions are still present, to ensure backwards compatibility, but marked …
> feat: Provide functional options for the client constructor

- clerk/clerk.go
- clerk/jwt_templates.go
- clerk/jwt_templates_test.go
- tests/integration/jwt_templates_test.go
Add support for the new JWT templates endpoints. The below operations are available:
- List all available JWT templates of an instance
- Read a single JWT template by ID
- Create a new JWT template
- Update an existing JWT template
- Delete an existing JWT template by ID
> feat: Support for jwt_templates endpoints

- clerk/clerk.go
- clerk/middleware_v2.go
- clerk/tokens.go
- clerk/tokens_options.go
- clerk/tokens_options_test.go
- clerk/tokens_test.go
Added support to verify the authorized party (azp) claim, if it's included in the session token claims within the VerifyToken method and v2 middlewares
> feat: Support to verify authorized party (azp) session token claim

- clerk/clerk.go
- clerk/users.go
- clerk/users_test.go
- tests/integration/templates_test.go
- tests/integration/users_test.go
This PR includes two changes:
* Adds some missing params on the list users which are supported by our BAPI endpoint. Namely, it allows to filter users based on web3 wallets, usernames, user ids or a query. It also allows to order users by particular properties.
* Adds the new users count endpoint which return the total count of users that match the filtering params given. This is particularly helpful for callers who need to know the total count in order to properly use the limit/offset capabilities of our list users method. _Please note_ that this is a temporary solution until we properly implement pagination responses.
https://www.notion.so/clerkdev/Return-user-total-count-in-BAPI-771264a4fccc461984f98003b0204499
> Added endpoint to get total count of users

- clerk/tokens.go
- clerk/tokens_options.go
- clerk/tokens_options_test.go
- clerk/tokens_test.go
This PR makes it possible to use Clerk's [JWT Verification Key](https://docs.clerk.dev/popular-guides/validating-session-tokens) in serverless environments.
The key can be constructed from PEM via https://pkg.go.dev/go.step.sm/crypto/jose#ParseKey
> Allow to verify tokens with preconfigured JWK

- clerk/organizations.go
- clerk/organizations_test.go
- tests/integration/organizations_test.go
This PR allows the organizations `ListAll` method to optional include the members count of each organization in the returned response.
> feat: Allow list all orgs to optionally include members count in the response

- README.md
- clerk/tokens.go
- clerk/tokens_options.go
- clerk/tokens_test.go
Introduce a new option WithCustomClaims for the VerifyToken() method. This will allow users to retrieve any custom claims that a token may contain after a successful verification.
https://github.com/clerkinc/clerk-sdk-go/issues/53
> feat: Introduce VerifyToken WithCustomClaims option

- clerk/clerk.go
- clerk/users.go
- clerk/users_test.go
- tests/integration/users_test.go
This commit adds a new function on the Users, called `UpdateMetadata`.
This is responsible for updating the metadata of the given user. This operation is additive, which means that you don't have to pass the whole metadata object, just the part you want to update/add and it will do the necessary action on its own.
> feat: Added Users.UpdateMetadata method

- clerk/clerk.go
- clerk/instances.go
- clerk/instances_test.go
- tests/integration/instances_test.go
Updated params of `Instances.Update` to include `support_email`.
This is the email address that will be displayed in the frontend, when the instance users require support.
> feat: Added support email on the settings that can be configured in an instance

- clerk/clerk.go
- clerk/redirect_urls.go
- clerk/redirect_urls_test.go
- tests/integration/redirect_urls_test.go
This commit adds a new service `RedirectURLs` which exposes the following methods:
* _Create_: Creates a new redirect url
* _ListAll_: Retrieves a list of all available redirect urls
* _Delete_: Deletes the given redirect url
> feat: Added methods for handling redirect urls

- clerk/instances.go
- clerk/instances_test.go
New `clerk_js_version` param support for the instance update operation.
If `""` is set, the value on the server will be cleared.
> feat: Support setting the clerk_js_version param for instance updates

- clerk/blocklists.go
- clerk/blocklists_test.go
- clerk/clerk.go
- tests/integration/blocklists_test.go
This commit adds functions to handle blocklists.
In particular, it includes the following:
* `CreateIdentifier`: Creates a new blocklist identifier. This identifier can be an email address or domain, a phone number or a web3 wallet.
* `ListAllIdentifiers`: Returns all blocklist identifiers
* `DeleteIdentifier`: Deletes the blocklist identifier that corresponds to the given id
> feat: Added blocklists in Go SDK

- clerk/allowlists.go
- clerk/allowlists_test.go
- clerk/clerk.go
- clerk/instances.go
- clerk/instances_test.go
- clerk/organizations.go
- tests/integration/allowlists_test.go
- tests/integration/instances_test.go
- tests/integration/organizations_test.go
This commit adds functions to handle allowlists.
In particular, it includes the following:
* `CreateIdentifier`: Creates a new allowlist identifier. This identifier can be an email address or domain, a phone number or a web3 wallet.
* `ListAllIdentifiers`: Returns all allowlist identifiers
* `DeleteIdentifier`: Deletes the allowlist identifier that corresponds to the given id
> feat: Added allowlists in Go SDK

- clerk/users.go
- clerk/users_test.go
Introduce `totp_secret` optional param for create user operation
https://www.notion.so/clerkdev/Allow-users-to-set-totp_secret-via-BAPI-POST-v1-users-1ff275fafbd840dfada44b3ed24045c8
> feat: Introduce totp_secret optional param for create user operation

- clerk/clerk.go
- clerk/instances.go
- clerk/instances_test.go
- tests/integration/instances_test.go
Added new method on instance service `UpdateOrganizationSettings` which allows users to update the instance's organization settings.
> feat: Added method on instance service to update organization settings

- clerk/clerk.go
- clerk/instances.go
- clerk/instances_test.go
- clerk/organizations.go
- tests/integration/instances_test.go
- tests/integration/organizations_test.go
This PR adds three new methods in the organizations service, to create, update and delete organizations.
It also allows users to configure the max allowed memberships on the instance level.
> Added methods for creating, updating and deleting organizations

- clerk/users.go
Add support for updating user's TOTP secret and backup codes
Also included the missing parameter for backup codes in create user endpoint
https://www.notion.so/clerkdev/Allow-updating-totp_secret-backup_codes-for-a-user-via-BAPI-77ed76eeed3d4681b54f04e2ae566016
> feat: Add support for updating user's TOTP secret and backup codes

- clerk/middleware.go
- clerk/tokens.go
- clerk/tokens_test.go
This commit adds support for the new issuer format we are going to introduce for our dev instances. The new format is `https://foo-bar-13.clerk.accounts.dev` when the old one would be `https://clerk.foo.bar-13.lcl.dev`
> feat: Support new issuer format for dev instances

- clerk/organizations.go
- clerk/organizations_test.go
The UpdateMetadata function is only allow us to append or modify the params, the deletions can be done only by setting the value of a property to null. This adds extra complexity to the front end in order to perform deletion. We modify the Update organizations function in order to receive metadata so we will be able to delete easier.
> feat: Allow organizations update to receive metadata

- tests/integration/organizations_test.go
Only changes on the `organizations_test.go`
We added some test cases to check if we can correctly update the organization metadata through the update function.
> chore: Add test for organization metadata

- clerk/instances.go
Now that dashboard has switched to using the `url_based_session_syncing` setting, marking `cookieless_dev` as deprecated.
> chore: Deprecate cookieless_dev setting

- clerk/organizations.go
- tests/integration/organizations_test.go
By adding UserID as param at ListAll organizations we can exclude or include this userID from the query.
> chore: Add UserID as filter param at organizations

- clerk/users.go
Fixes issue with incorrect type on UpdateUserMetadata which is currently set to `interface{}` to `json.RawMessage` which is what is needed to make the request work however anything currently passed into it such as a map[string]string is currently valid.
https://github.com/clerkinc/clerk-sdk-go/issues/109
> fix: Change UpdateUserMetadata to proper type

- clerk/instances.go
- tests/integration/instances_test.go
We add the development_origin to the update instance params. If this param is set is going to override our default origin url in development instances
Also we fix a failing test at `users`
> chore: Add development_origin to update instance

- clerk/instances.go
- clerk/instances_test.go
- tests/integration/instances_test.go
This commit adds a new instance setting to control whether users are allowed to sign up on their own, or sign ups are disabled which means that users can only be added by an administrator.
> Added new instance setting to control whether sign ups are disabled

- clerk/clients.go
- clerk/clients_test.go
]## Type of change
Remove two deprecated fields of client response
- `sign_in_attempt_id`
- `sign_up_attempt_id`
> chore: Remove deprecated client.sign_in_attempt_id & client.sign_up_attempt_id fields

- clerk/clerk.go
- clerk/saml_connections.go
- clerk/saml_connections_test.go
- clerk/users.go
This commit fixes the SAML Connection ListAll() method, to return the proper data (paginated) and to also accept any pagination params that the user might want to use
> fix: SAML Connection response type and accept pagination params

- clerk/instances.go
- clerk/instances_test.go
- tests/integration/instances_test.go
This commit removes the option of disabling sign ups, given that it's a feature that was never implemented and thus not used by anyone.
> chore: Removed non-implemented disable sign ups option

- clerk/http_utils_test.go
- clerk/saml_connections.go
- clerk/saml_connections_test.go
- clerk/users_test.go
This PR contains 3 different commits that handle the below:
1. Fix the recent incompatibility change by using the url value [`Has()`](https://pkg.go.dev/net/url#Values.Has) method which was introduced in go1.17 but we are still in go1.16
2. Introduce some handy test helpers to convert int & string types to the equivalent pointer types
3. Include the new saml connection fields `provider`, `user_count` and add support for `query`, `order_by` params in ListAll() method
> Include saml connection 'provider', 'user_count' fields and add support for 'query', 'order_by' params in ListAll() method

- tests/integration/templates_test.go
There's no need to verify that each template can be upserted. As long as we can verify that the templates.Upsert() method works for at least one template we have good enough test coverage.
> chore: Make our templates test resilient to change

- clerk/instances.go
- clerk/organizations.go
Update SDK to include new `admin_delete_enabled` param for both organization settings and organizations
> feat: Update organization settings params to include admin_delete

- clerk/saml_connections.go
- clerk/saml_connections_test.go
This commit modifies the SAML Connection create operation params, to convert the IdP related ones (IdpEntityID, IdpSsoURL, IdpCertificate) to optional as we have changed our BAPI endpoints. This is a breaking change, but the feature is still in Beta
> fix: IdP related data are optional during SAML Connection create

- clerk/instances.go
- tests/integration/instances_test.go
Added support for the `block_email_subaddresses` key in the instance restrictions response.
I should have been more careful in #150. :disappointed:
> fix: Include block email subaddresses in restrictions response

- clerk/instances.go
- clerk/instances_test.go
In this commit we are introducing two new parameters (domains_enabled, domains_enrollment_modes) as part of the update organization settings method, in order to control organization domain related settings
> feat: Allow updating organization domain related settings (enable, enrollment modes

- clerk/instances.go
We add the omitempty tag on the domains_enrollment_modes field of UpdateOrganizationSettings() method in order the marshaller to not convert the field to 'null' value if not provided
> fix: Add omitempty tag on domains_enrollment_modes field of UpdateOrganizationSettings()

- clerk/instances.go
- clerk/instances_test.go
- tests/integration/instances_test.go
Add `block_disposable_email_domains` parameter for `https://api.clerk.com/v1/instance/restrictions` endpoint.
> feat: Add block_disposable_emails param

- README.md
- clerk/middleware.go
- clerk/tokens.go
- clerk/tokens_issuer.go
- clerk/tokens_options.go
- clerk/tokens_options_test.go
- clerk/tokens_test.go
The js sdk [1] supports overriding the expected issuer by allowing the
sdk user to set a couple of options.
This makes the issuer verification possible for a couple of non-standard
ways, namely when the customer's fapi sits behind a proxy or when the
domain is not the primary one.
[1] https://github.com/clerkinc/javascript/blob/c7c6912f34874467bc74104690fe9f95491cc10d/packages/backend/src/tokens/interstitialRule.ts#L158-L170
Fix USR-388
>  Modify Issuer verification for all possible scenarios

- README.md
- clerk/middleware.go
- clerk/middleware_v2.go
- examples/middleware/main.go
WithSessionV2/RequireSessionV2 are for quite some time the de-facto way to use Clerk. Therefore, deprecate WithSession and update examples to use WithSessionV2 instead.
Resolves #154
> docs: Deprecate the old middleware

- clerk/clerk.go
- clerk/proxy_checks.go
- clerk/proxy_checks_test.go
- tests/integration/proxy_checks_test.go
Added a ProxyChecksService with a method to Create a proxy check. Triggers a request to the Backend API POST /v1/proxy_checks endpoint.
> feat: Proxy checks service

- clerk/instances.go
- clerk/instances_test.go
Add ability to change`creator_role` when updating organization settings
> Update organization creator role

- clerk/instance_organization_permissions.go
- clerk/instance_organization_permissions_test.go
- clerk/instance_organization_roles.go
- clerk/instance_organization_roles_test.go
- clerk/permissions.go
- clerk/roles.go
In this commit we align the naming for the Role and Permission resources with the rest of our SDKs. We will use a more generic term of Role and Permission for every related endpoint
**The feature that uses these endpoints are under active development, thus these changes are not considered breaking**
> chore: Align naming for Roles and Permissions

- clerk/instance_organization_roles.go
- clerk/instance_organization_roles_test.go
In the previous commit we missed to rename the struct we are using to update an instance organization role as well
**The feature that uses these endpoints are under active development, thus these changes are not considered breaking**
> chore: Rename UpdateInsOrgRoleParams to UpdateInstanceOrganizationRoleParams

- clerk/instances.go
- clerk/instances_test.go
We update the logic of the instance organization settings method in order to accept a role ID instead of a Key for the default creator role. This is because we should use an immutable identifier instead of the Key which customers are able to modify
> fix: Accept role ID instead of Key for organization settings creator role

- clerk/instance_organization_permissions.go
- clerk/instance_organization_permissions_test.go
Add read, create, update, delete endpoints for custom permission
> feat: Add support for BAPI custom permissions endpoints

- clerk/instance_organization_permissions.go
- clerk/instance_organization_permissions_test.go
- clerk/instance_organization_roles.go
- clerk/instance_organization_roles_test.go
As part of the List operations for Organization Roles & Permissions, we now support the 'order_by' & 'query' parameters along with the regular pagination
> feat: Support 'order_by' & 'query' parameters on Organization Role & Permission List methods

- clerk/tokens.go
- clerk/tokens_test.go
When decoding and verifying a session token, we are now parsing any organization permissions that might be included and make them available as part of the SessionClaims struct
> feat: Add active organization's permission in session claims

- clerk/instance_organization_roles_test.go
- clerk/roles.go
We expose a new property as part of the role response, which denotes if the role can be used as the default organization creator role. We also align the dummy Role JSON objects with real response objects
> feat: Denote if organization role can be used as the creator

- clerk/instances.go
As the 'domains_default_role_id' is an optional property, we should use the omitempty tag in order to end up with an empty string as the request body
> fix: Add omitempty tag on 'domains_default_role_id' property for updating the instance organization settings

- README.md
- clerk/http_utils_test.go
- clerk/users.go
- clerk/users_test.go
- The query parameter `last_active_at_since` can now be used to filter users based on their latest session activity date.
- Field `last_active_at` is now included in the User response fields.
> feat: Introduce users.last_active_at field and allow filtering in List

- README.md
Closes #194
- Add documentation and example for injecting a custom `*http.Client` instance for use by the SDK methods.
Closes #194
> chore: Update README to include Client constructor options

- clerk/session_claims.go
- clerk/session_claims_test.go
- clerk/tokens.go
Add `HasPermission()` and `HasRole()` to session claims
> feat: Add session claims helper methods to check roles and permissions

- clerk/instances.go
- clerk/instances_test.go
There is a maximum number of organization roles and permissions that you can create per instance. Expose those properties as part of the instance organization settings response
> feat: Expose max allowed organization roles and permissions properties

- clerk/saml_connections.go
- clerk/saml_connections_test.go
We update our SAML Connection Create() method in order to also require the 'provider' property as Backend API from now on requires to be present. 
_This is a breaking change as it concerns the API, but the SAML feature is still in Beta_
> feat!: When creating a SAML Connection you are also required to provide the provider type

- clerk.go
- deleted_resource.go
- domain.go
- domain/domain.go
- domain/domain_test.go
Added types for Domains. 
Added a new package for Domains API operations. Supports List, Create, Update and Delete.
> feat: Domains API operations

- actor_token.go
- actortoken/actor_token.go
- actortoken/actor_token_test.go
- clerktest/clerktest.go
- domain/domain_test.go
Added the types and operations for actor tokens. Create and Revoke are supported.
> feat: Actor token API operations

- actortoken/actor_token.go
- clerk.go
- clerk_test.go
- domain/domain.go
Changed the Queryable interface to Params. Instead of operating on a url.Values object, implementing types should return a url.Values object. When we set the params to the querystring, we'll use the new interface method.
Added a custom implementation to join URL paths. The new implementation will preserve any query parameters in the URL. We can now replace url.JoinPath, which required us to use Go v1.19 and upwards.
> fix: Params interface

- allowlist_identifier.go
- allowlistidentifier/allowlist_identifier.go
- allowlistidentifier/allowlist_identifier_test.go
Added types for allowlist identifiers and API operations for Create, Delete and List.
> feat: Allowlist identifiers API operations

- clerk/saml_connections.go
- clerk/saml_connections_test.go
As part of the SAML Connection Create and Update operations, allow to define the attribute mapping of IdP properties to Clerk's user properties
> feat: Support define SAML Connection Attribute mapping

- jwt/jwt.go
- jwt/jwt_test.go
The jwt.Verify method needs to fetch the JSON Web Key Set from the API in order to verify the session JWT's validity. 
The jwt.Verify method is used in the http.WithHeaderAuthorization middleware, which means that in an HTTP server context, the method will executed for every request.
We're adding a caching layer for the JWKS when we verify the session JWT. This way we can cache the JWKS response from the API for 1 hour.
> feat: Cache requests for JWKS on JWT verification

- clerk/sessions.go
- clerk/sessions_test.go
- Add clerk backend [api endpoint](https://clerk.com/docs/reference/backend-api/tag/Sessions#operation/CreateSessionTokenFromTemplate) implementation to create a session token given a jwt template slug
> feat: Add create session token given a template slug endpoint

- clerk/saml_connections.go
- clerk/saml_connections_test.go
We now expose a new property 'allow_subdomains' as part of the SAML Connection response. You can also define it during Create and Update operations. Default value is false
> feat: Introduce 'allow_subdomains' SAML Connection property

- http/middleware.go
- http/middleware_test.go
- jwt/jwt.go
The JWT verification function accepts a handler that can be used to validate the 'azp' claim of the token.
The WithHeaderAuthorization middleware accepts either a handler or a list of authorized parties that must contain the 'azp' claim.
You can use the option in two ways.
```go
func checkAZP(azp string) bool {
// do whatever you want with the azp claim
}
WithHeaderAuthorization(AuthorizedParty(checkAZP))
// OR
// This will check that the 'azp' claim is one of the provided values
WithHeaderAuthorization(AuthorizedPartyFunc("clerk.com", "clerk.dev"))
```
> feat: Handler to check azp claim

- clerk.go
- clerk_test.go
Changed the User-Agent header to match the rest of our SDKs. The pattern is package@version.
> fix: Change User-Agent header

- clerktest/clerktest.go
- http/middleware.go
- jwt.go
- jwt/jwt.go
- jwt/jwt_test.go
Replaced the CustomClaims parameter with a CustomClaimsConstructor function when verifying a session JWT. The option is also available in the HTTP middleware.
The constructor function will be called when the JWT is parsed, producing a new struct instance instead of writing on a single instance. 
The custom claims will be made available in the SessionClaims.Custom field.
> feat: JWT parsing with custom claims

- clerk.go
- clerk_test.go
Added the ability to provide application-specific info in API request headers.
The X-Clerk-Application header can contain a unique identifier for an application, such as its domain or ID.
Use of this header will allow us to quickly filter requests, debug and resolve support issues easier.
> feat: Custom request header with application info

- README.md
- http/middleware.go
- jwk.go
- jwt.go
- jwt/jwt.go
- jwt/jwt_test.go
- jwt_test.go
Made sure that no go-jose types are exported from our package. 
Had to add more exported types for JWT claims, so that we can re-use go-jose's unmarshaling features.
We now have the following types for JWT claims:
- **RegisteredClaims** These are 'standard' public JWT claims registered in IANA.
- **Claims** These are Clerk-specific private claims, like session ID and active organization ID.
- **SessionClaims** These are the claims that are included in Clerk issued JWTs. They include RegisteredClaims, Claims and any other Custom keys from custom JWT templates. 
Another change introduced here is that the jwt.Decode function will now expose the Key ID header, if the JWT contains it. 
We need access to the kid header when implementing a custom JWT verification flow and jwt.Decode already does …
> fix: Don't expose jose types

- http/middleware.go
- http/middleware_test.go
Instead of returning a AuthorizedPartyHandler, the AuthorizedPartyMatches function will now set the AuthorizedPartyHandler parameter directly.
The different return type of AuthorizedParty and AuthorizedPartyMatches caused confusion.
> fix: http.AuthorizedPartyMatches sets middleware params

- clerk/saml_connections.go
- clerk/saml_connections_test.go
We now expose a new property 'allow_idp_initiated' as part of the SAML Connection response. You can also define it during the Update operation. Default value is false
> feat: Introduce 'allow_idp_initiated' SAML Connection property

- README.md
It's possible that users who land on the repository README are already using the SDK. 
It's a good idea to show a link at the top with upgrade instructions.
> chore: Added a link to the upgrade guide in README

- README.md
- UPGRADING.md
- v2_migration_guide.md
Changed the UPGRADING guide for the v1 to v2 migration to be more concise and mention specifically what changed need to be done. 
Left the old content as a "v2 migration guide" document, which explains the reasoning behind the rewrite with more details.
> fix: Concise upgrade instructions

- jwks/client.go
Fixed a bug where the jwks.Client.Get method would use the default Backend instead of the one attached to the client.
> fix: JWKS API uses client

- http/middleware.go
Applying authentication options should happen inside the handler to avoid the authorization parameters from getting mutated on each handler execution.
This was caught by a test in an upcoming PR. Sadly, it's hard to write a test to catch the bug here.
> fix: Auth middleware params should not be mutated

- .github/workflows/semgrep.yml
Add semgrep in monitoring mode to scan for security issues in the background such as:
- Committed secrets
- First-party code vulnerabilities
- Dependency vulnerabilities
> chore: add github action for semgrep to run security scans in monitoring mode

- clerk.go
- go.mod
- go.sum
- http/middleware.go
- http/middleware_test.go
- jwt/jwt.go
- v2_migration_guide.md
Verifying a session JWT includes time sensitive validations, like checking token expiration, or that the token can be used now ('nbf' claim).
The HTTP middleware caches JSON web keys for one hour. After that, the cache is considered invalid and a new request to fetch the JSON web key set will be issued.
These are both flows that depend on the current time and time comparisons.
Various system architectures with a distributed nature might not be synchronized. A clock skew is expected.
In such cases it's common to share a "time source" so that all nodes can coordinate on what the perceived current time is.
This commit adds a new clerk.Clock interface which can be passed as a dependency in the http middleware functions and the jwt.Verify function. We also add a dependency to the clockwork …
> feat: Clock interface as a time source

- UPGRADING.md
- clerk.go
- v2_migration_guide.md
Similar to our clerk.String, clerk.Bool and clerk.Int64 helpers, this commit adds a clerk.JSONRawMessage function that returns a pointer of the provided json.RawMessage value.
> feat: Helper for json.RawMessage pointers

- clerk.go
Calling the UTC() method when getting the current time might be helpful in time zone conversions.
> fix: Return the current time in UTC

- clerk/saml_connections.go
- clerk/saml_connections_test.go
Our SAML Connection Create/Update operations now accepts a new optional property 'IdpMetadata' which you can use in order to configure an IdP using the metadata file. If provided, we also include it in the response as well
> feat: Allow SAML Connection configuration with IdP Metadata

- UPGRADING.md
- http/middleware.go
- jwt/jwt.go
- jwt/jwt_test.go
- v2_migration_guide.md
In order to reduce friction when manually verifying a session JWT, the jwt.Verify function will fetch the JSON web key if it's not passed in the params.
Users can specify the jwks.Client that will be used to invoke the API GET /v1/jwks method.
Exported the method which fetches the JSON web key, since it can be re-used by the middleware. It can also be used for consumers who wish to fetch the JSON web key once and cache it. Caching is recommended.
```go
// Fetch the JWK once
decoded, _ := jwt.Decode(ctx, &jwt.DecodeParams{Token: token})
jwk, _ := jwt.GetJSONWebKey(ctx, &jwt.GetJSONWebKeyParams{KeyID: decoded.KeyID})
// Use the JWK to verify the token
claims, _ := jwt.Verify(ctx, &jwt.VerifyParams{
Token: token,
JWK: jwk,
})
```
> feat: jwt.Verify fetches the JSON web key

- samlconnection/client.go
- samlconnection/client_test.go
The List operation of the SAML connections API supports pagination with limit and offset query string parameters.
> fix: Pagination parameters for samlconnection.List

- samlconnection/client.go
- samlconnection/client_test.go
Listing SAML connections also supports `query` and `order_by`.
This PR includes these two options.
> fix: Adds missing params for listing SAML connections

- oauth_access_token.go
- user/client_test.go
Add support for the new field in the OAuth access token response.
> feat: Add `external_account_id` to OAuth access token response (v2)

- clerk/users.go
- clerk/users_test.go
Add support for the new field in the OAuth access token response.
> feat: Add `external_account_id` to OAuth access token response

- clerk.go
- clerk_test.go
- http/middleware_test.go
- jwt/jwt_test.go
The /v1/ part of API endpoint paths will no longer signal the API version. It can be considered part of the base API URL.
All requests set the Clerk-API-Version header to pin the SDK to a specific API version.
> API base URL and versioning

- clerk.go
- clerk_test.go
Updated the clerk.JoinPath method to trim slashes only at the end of URLs.
> fix: Trim only trailing slashes in URLs

- clerktest/clerktest.go
- go.mod
- go.sum
- http/middleware_test.go
Removed the clockwork dependency in favor of a custom test clock implementation.
We don't need all the functionality that the clockwork module has to offer and it's best we keep dependencies to a minimum.
> feat: Test clock

- user/api.go
- user/client.go
- user/client_test.go
Changed the user.ListOrganizationMemberships API operation so that the user ID is provided as a separate parameter, avoiding confusion as to which resource the ID refers to (user, organization or organization membership).
> fix: User list memberships id

- http/middleware.go
- http/middleware_test.go
Added an option to the http.WithHeaderAuthorization middleware to modify the default response in case of authentication failure.
Fixes #277.
> feat: Custom authorization failure handler

- clerk/instances.go
- clerk/instances_test.go
- tests/integration/instances_test.go
- **feat: add IgnoreDotsForGmailAddresses restriction on sdk**
- **test: IgnoreDotsForGmailAddresses restriction**
> **DO NOT MERGE**
>This PR depends [on](https://github.com/clerk/clerk_go/pull/6369)
> Add IgnoreDotsForGmailAddresses on SDK restriction resource

- clerk.go
- clerk_test.go
Prior to this, if the [clerk backend config url](https://github.com/clerk/clerk-sdk-go/blob/2d117c9e9511d5e460a408ff958af45c179d2b1e/clerk.go#L182) was left as empty, the SDK would prepend an extra `/` to all paths. So a request to `/foo` would become `//foo`.
This change updates our slash-stripping regex to remove leading slashes from the final URL.
> Allowing the base url to be empty

- template.go
~`template.can_disable`~ (`template.can_toggle`) permission will instruct the front end on whether it can show a toggle to disable a template.
`template.enabled` shows the enabled status of a template.
> feat: Expose template.enabled property & can_toggle permission

- clerk/sessions.go
- clerk/sessions_test.go
This function throws error with response 404.
Referring this API from docs: https://clerk.com/docs/reference/backend-api/tag/Sessions#operation/CreateSessionTokenFromTemplate
... seems to be typo in the url.
Validation - confirmed working by following ways:
- Used the "try it" in the above API docs link - worked !
- Created my own function for this using the same `clerk.Client.Req/Do` and updated URL - worked !
> Sessions: Fix typo in tokens url for CreateTokenFromTemplate
