clerk/clerk.go, clerk/clerk_test.go, clerk/errors.go, tests/integration/clerk_test.go, tests/integration/verification_test.go
=> Modified Go SDK to conform to Clerk's new error structure

README.md
Server API is now Backend API and the links were broken.
=> Update README links to backend API docs

clerk/templates.go, clerk/templates_test.go, tests/integration/templates_test.go
Template payload will contain a list of available & mandatory variables.
**available:** the whole set that CAN be used in the template body
**mandatory:** the bare minimum that MUST be used in the template body (e.g. the code for a verification code message)
This will no longer be updatable, so removing from update payload.
=> fix: Support for revised template variable payload

clerk/middleware.go
We already do support it in WithSessionV2, so we should do so here too.
=> fix: Support "Bearer <token>" in AuthV2 middleware

clerk/middleware_v2.go, clerk/middleware_v2_test.go
This PR contains the below changes:
1. For development/staging environments, try to detect if that's a non-browser request (e.g. script) based on the request `User Agent` and prevent interstitial rendering
2. Take into account the `Authorization` header every time it exists in the request
#35
=> feat: Support non-browser requests for development/staging environments

clerk/jwt_templates.go, clerk/jwt_templates_test.go
This PR adds support for configurable signing keys in JWT Templates.
=> feat: Support for JWT Templates signing key/algo

README.md
Update broken link for Backend API in readme
=> doc: Update readme broken Backend API link

clerk/clerk.go
Add custom header `X-Clerk-SDK` in every request which contains the current SDK version with the following format `go/<version>`
=> feat: Add custom header X-Clerk-SDK in request for SDK version

clerk/clerk.go, clerk/http_utils_test.go, clerk/sessions.go, clerk/tokens.go, clerk/tokens_test.go, clerk/users_test.go, clerk/verification.go, clerk/verification_test.go, examples/middleware/main.go, examples/operations/main.go, tests/integration/clerk_test.go, tests/integration/clients_test.go, tests/integration/emails_test.go, tests/integration/jwt_templates_test.go, tests/integration/sessions_test.go, tests/integration/sms_test.go, tests/integration/templates_test.go, tests/integration/users_test.go
I'm planning to contribute some changes and noticed that the code isn't formatted consistently.
Used `gofumpt -w -extra ./clerk/ ./examples/ ./tests/` to do just that.
=> Format code with gofumpt

clerk/templates.go, clerk/templates_test.go, clerk/users.go, clerk/users_test.go
=> feat: Add user.last_sign_in_at & template.resource_type to payloads

clerk/clerk.go, clerk/organizations.go, clerk/organizations_test.go, tests/integration/organizations_test.go
Updated SDK to include a list all and a count operation on the organizations resource.
=> chore: Added organizations list all and count

clerk/clerk.go, clerk/instances.go, clerk/instances_test.go, tests/integration/instances_test.go
Added a new `Instances.Update` method which allows the caller to update certain instance settings on the respective instance.
=> feat: Added function to update certain instance settings

clerk/clerk.go, clerk/instances.go, clerk/instances_test.go, tests/integration/instances_test.go
=> Configure instance's enhanced deliverability mode

clerk/clerk.go, clerk/users.go, clerk/users_test.go, tests/integration/users_test.go
=> feat: Added unsafe metadata to user object

clerk/clerk.go, clerk/users.go, clerk/users_test.go
Added new method in users service to allow user creation.
=> feat: Added operation in users service to create new users

clerk/allowlists.go, clerk/allowlists_test.go, clerk/blocklists.go, clerk/blocklists_test.go, clerk/clerk.go, tests/integration/blocklists_test.go
=> feat: Include identifier_type in allowlists and blocklists

clerk/clerk.go, clerk/impersonation_tokens.go, clerk/impersonation_tokens_test.go, tests/integration/impersonation_tokens_test.go
Added new service to handle impersonation tokens.
More specifically, the `ImpersonationTokens()` service gives you access to methods for creating and revoking impersonation tokens.
=> feat: Added service for impersonation tokens

clerk/users.go, clerk/users_test.go
Introduce a new user operation `DisableMFA` which disables all user's MFA methods
https://www.notion.so/clerkdev/Deactivate-2FA-from-BAPI-c9c85987e8ce464baa703dcc77ea0360
=> feat: Introduce operation to disable user's MFA methods

clerk/clerk.go, clerk/users.go, clerk/users_test.go, tests/integration/clerk_test.go, tests/integration/users_test.go
=> Added operations for ban and unban users

clerk/users.go
Introduce `user.TOTPEnabled` & `user.BackupCodeEnabled` fields
=> feat: Introduce user.TOTPEnabled & user.BackupCodeEnabled fields

clerk/clerk.go, clerk/tokens.go, clerk/tokens_test.go
=> feat: Added org claims in session token

clerk/users.go
Add password digest & password hasher fields in create user params
=> feat: Add password digest & hasher in create user params

clerk/clerk.go, clerk/email_addresses.go, clerk/email_addresses_test.go, clerk/phone_numbers.go, clerk/phone_numbers_test.go, clerk/users.go, clerk/verification.go, go.mod, go.sum, tests/integration/email_addresses_test.go, tests/integration/phone_numbers_test.go
Adds support for the following `email_address` operations:
* Create
* Read
* Update
* Delete
Adds support for the following `phone_number` operations:
* Create
* Read
* Update
* Delete
=> feat: Add support for email_address & phone_number CRUD operations

clerk/instances.go
=> feat: Add cookieless_dev setting in InstanceUpdate

clerk/middleware_v2.go
=> fix: Respect verify token options in middleware

clerk/organizations.go, clerk/organizations_test.go
- [] 🐛 Bug fix (non-breaking change which fixes an issue)
If this PR applied it will allow us to fetch all the details for a single organization.
@gkats
=> chore(organizations): Add Read functionallity for organization

clerk/middleware_v2.go
Upcoming secret keys will start with `sk_` prefix, so adding support for that format in `isDevelopmentOrStaging` as well.
=> feat: Support new secret key format in isDevelopmentOrStaging check

clerk/organizations.go
If this PR applied it will add a function to be able to update an organization metdata.
=> chore: Add UpdateMetadata for organization

clerk/organizations.go, tests/integration/organizations_test.go
Introduce a new function that will allow us to retrieve the memberships of an organization.
=> feat: Add get organization memeberships function

clerk/organizations.go, tests/integration/organizations_test.go
Introduce two new functions that will allow us to update and create memberships.
=> Add Create and Update membership functions.

clerk/organizations.go, tests/integration/organizations_test.go
`ListMembership()` now can be used to filter the expected results,using query,email etc
=> chore: Populate ListMemberships function to accept params.

clerk/organizations.go, tests/integration/organizations_test.go
Add role as search param to filter the memberships list
=> chore: Add role search param for meberships

README.md
Previous link to backend API reference was outdated.
=> refactor: update README to use correct backend API docs link

clerk/organizations.go, clerk/organizations_test.go, tests/integration/organizations_test.go
Add `query` param to support organizations filtering
=> feat: Add organizations filter param

clerk/organizations.go, clerk/organizations_test.go, tests/integration/organizations_test.go
Added the CreatedBy string property to the Organization resource.
=> feat: Add Organization.CreatedBy

CODEOWNERS, clerk/middleware_v2.go
Set signed-out as default request state and return interstitial ONLY when the token verification fails with expired or invalid_iat errors.
Extra actions:
=> fix: interstitial of failed token verification

README.md
=> Migrate README urls to clerk.com

clerk/instances.go, tests/integration/templates_test.go
We add UpdateHomeURL function that will allow us to update the domain url of the instance.
=> chore: Add UpdateHomeURL function

clerk/users.go
Added two new fields to the users.Update() method payload.
- SkipPasswordChecks will ignore the instance's password policy when updating the user's password.
- SignOutOfOtherSessions will sign out the user of all their active sessions when the password is updated.
=> feat: Update user control password settings

clerk/organizations.go
Parse `image_url` experimental field from Clerk server response.
=> feat: Add image_url in organizations responses

clerk/organizations.go
Add `image_url` in organization memberships public user metadata.
=> feat: Add image_url in PublicUserData of organizationsMemberships response

clerk/http_utils_test.go, clerk/sessions.go, clerk/sessions_test.go, examples/operations/main.go
Add Filtering to `Sessions().ListAll()` to match the API. 
#125
=> Add filtering to Sessions().ListAll()

clerk/organizations.go, tests/integration/organizations_test.go, tests/integration/templates_test.go
We Introduce a new parameter order_by that will allow us to order the organizations and organization memberships
=> chore: Add support of order by at organizations

clerk/clerk.go
Introduce order_by for organization memberships and organizations
=> chore: Release 1.41.0

clerk/saml_connections.go, clerk/saml_connections_test.go
Introduce a new SAML Connection field `sync_user_attributes` and modify the Update method in order to be able to define it and update it as well
=> feat: Introduce new sync_user_attributes SAML Connection field and ability to update it

clerk/organizations.go, tests/integration/organizations_test.go
This commit adds `slug` to update organization params
=> chore: Add slug to update organization params

clerk/clerk.go
=> chore: Release v1.43.0

clerk/clerk.go
=> chore: Release 1.44.0

clerk/organizations.go, clerk/organizations_test.go, tests/integration/organizations_test.go
Added a new DeleteLogo() method on the organizations service. 
Accepts the organization ID as a parameter and removes the logo from the organization.
=> feat: Delete organization logo

clerk/clerk.go
=> Release v1.45.0

clerk/clerk.go, clerk/domains.go, clerk/domains_test.go, tests/integration/domains_test.go
We introduce the domains service.
Ref USR-92
=> feat: Introduce domains

clerk/clerk.go
=> Release v1.46.0

clerk/organizations.go, clerk/users.go
Support `HasImage` in User and Organization
=> Support `HasImage` in User and Organization

clerk/clerk.go
Bumped version to 1.47.0.
Changelog:
- Support `HasImage` in User and Organization #147
- Fix missing `ImageURL` in User  #147
=> Release v1.47.0

clerk/clerk.go
=> chore: Release v1.48.0

clerk/sessions.go
=> Fix #159 - expose more session fields

clerk/users.go
This adds support for the `ExternalIDs` parameter, which is supported on the Backend API as [per its API reference](https://clerk.com/docs/reference/backend-api/tag/Users#operation/GetUserList!in=query&path=external_id&t=request).
=> feat(users): expose ExternalIDs as list param

clerk/templates.go
Allow toggling of delivery by Clerk per template as an individual operation.
=> feat(templates): Implement toggle_delivery operation

actor_token.go
Added the ActorToken.URL field.
Fixes #201
=> fix: Include actor token URL

proxycheck/client.go
Deprecate the proxycheck package and the Create operation.
=> fix: Deprecate Proxy Checks API

CHANGELOG.md, UPGRADING.md
Added upgrade guide and changelog templates for the library. 
Added an entry in the upgrade guide for migrating from v1 to v2.
=> feat: Upgrade guide

.github/workflows/semgrep.yml
@gkats duplicating #264 for v2
=> chore: add github action for semgrep to run security scans in monitoring mode

README.md
=> chore: Exit beta

README.md
Updating Clerk open positions page.
https://jobs.ashbyhq.com/clerk
=> docs: changing clerk hiring page

instance_settings.go, instancesettings/client.go
=> feat: add ignore_dots_for_gmail_addresses for instance settings struct
